### ISSUE TITLE
希望在管理界面端加入赠送ai币模式

### ISSUE THREAD

**Issue by 6745060** [dulaiduwang003/TIME-SEA-WEB#1]

**Comment by 6745060** [comment]
我的ai币用完了，只能重新注册账号，希望管理端加个可以赠送ai币的功能或者是兑换码之类的

**Comment by xjy1592922966** [comment]
好，下一个迭代做。 因为原来是考虑充值。 如果你想给自己加币， 可以尝试sql直接加。

**Comment by 6745060** [comment]
还有管理端在加个公告模式，可以自定义，注册方式再加个方式，还有再加个忘记密码功

**Comment by xjy1592922966** [comment]
好的， 有啥想要的功能，可以在这个贴留下来， 后期专门做一个list，迭代这些功能.
注册方式这边可能短时间内都是用邮箱，如果补充一个新注册方式可能就是手机号， 那个需要加一个加密方式再做可能会靠谱一些，纯MD5有点不靠谱
