### ISSUE TITLE
后端最后一步JAVA输出打包问题

### ISSUE THREAD

**Issue by TickCAI** [dulaiduwang003/TIME-SEA-WEB#2]
后端最后一步，输出打包，代码跑完了没有报错，为啥没有Java包

**Comment by xjy1592922966** [comment]
图也没有，日志也没有，操作步骤也没有，解决不了

**Comment by coder-xbai** [comment]
![image](https://github.com/dulaiduwang003/SUPERBOT-GPT-WEB/assets/64308128/e35ff322-7c1e-41d2-9111-e1061bcafd61)
在运行打包命令后还是出现这种错误，
本地java是1.8版本，然后
在pom文件中将改成了  <source>18</source>
                    <target>18</target>
version中也改了，但是还是错误

**Comment by xjy1592922966** [comment]
你要进入java目录执行打包命令，

**Comment by coder-xbai** [comment]
这已经是在SUPER_JAVA目录下打包后的结果

**Comment by xjy1592922966** [comment]
![image](https://github.com/dulaiduwang003/SUPERBOT-GPT-WEB/assets/17585645/f4918d2a-23ad-4184-bd7d-a1bde964cb5b)

SUPER_JAVA目录下打包应该不是这个报错，  图片的路径也不正确，

**Comment by coder-xbai** [comment]
![image](https://github.com/dulaiduwang003/SUPERBOT-GPT-WEB/assets/64308128/c01a6154-9a06-4452-946c-065ae67343a4)

**Comment by coder-xbai** [comment]
![image](https://github.com/dulaiduwang003/SUPERBOT-GPT-WEB/assets/64308128/9034768b-caa3-4637-96b1-4b1409d762ff)
![image](https://github.com/dulaiduwang003/SUPERBOT-GPT-WEB/assets/64308128/da191559-6eb6-4c31-bb39-ed9350743ae4)

我本地java环境是1.8 ,这里更换后还是报同样的错误
![image](https://github.com/dulaiduwang003/SUPERBOT-GPT-WEB/assets/64308128/867da438-73cf-48e3-89d0-4e461ad2b055)

**Comment by xjy1592922966** [comment]
导致这个原因出现是因为当前项目的JDK版本与  配置的JDK环境版本不一样导致的


电脑的java 建议使用 openjdk 19  线上也用 openjdk19   配置文件里面不用改 

openjdk下载链接

https://jdk.java.net/19/

**Comment by xjy1592922966** [comment]
如果操作比较困难， 可以直接看 readme里的哔哩哔哩 喂饭视频， 里面是0到1的，可以2倍速看，尽量不要跳
