### ISSUE TITLE
部署后报错，管理员无法登陆

### ISSUE THREAD

**Issue by WinsCat** [dulaiduwang003/TIME-SEA-WEB#5]
Failed to load resource: the server responded with a status of 404 ()
不知道什么原因 post的是前端域名 不知道对不对

**Comment by xjy1592922966** [comment]
post的目标地址得是后端域名的才对，  前端没有做转发也没有伪静态哈， 需要前端重新打包

**Comment by WinsCat** [comment]
> 

OK 已经搞定 另外在宝塔部署的时候还有一个跨域问题 配置文件增加了

**Comment by WinsCat** [comment]
感谢已经搞定 另外在宝塔部署时候产生了跨域问题 新增配置已解决
add_header 'Access-Control-Allow-Origin' '*';
add_header 'Access-Control-Allow-Credentials' 'true';
add_header 'Access-Control-Allow-Methods'  'GET, POST, OPTIONS';
