### ISSUE TITLE
部署后，无法返回消息，token是用的自己的

### ISSUE THREAD

**Issue by liuzhongyyi** [dulaiduwang003/TIME-SEA-WEB#7]
![image](https://github.com/dulaiduwang003/SUPERBOT-GPT-WEB/assets/41277860/86c5443c-7735-4cd5-bf6e-dd858c85953d)
返回的是101

**Comment by liuzhongyyi** [comment]
![image](https://github.com/dulaiduwang003/SUPERBOT-GPT-WEB/assets/41277860/1a5da24f-4d69-4175-a16c-47ce76f74ba8)

**Comment by xjy1592922966** [comment]
这是符合预期的， 看java项目日志

**Comment by liuzhongyyi** [comment]
![image](https://github.com/dulaiduwang003/SUPERBOT-GPT-WEB/assets/41277860/ce87b12e-3f24-4e2f-89e7-0f689026dc8b)

**Comment by liuzhongyyi** [comment]
是因为代理问题吗

**Comment by xjy1592922966** [comment]
需要登录管理员界面，配置“记忆倍数”

**Comment by liuzhongyyi** [comment]
![image](https://github.com/dulaiduwang003/SUPERBOT-GPT-WEB/assets/41277860/ea6fb5aa-8cbd-4553-8917-18bbd0b1191f)

**Comment by liuzhongyyi** [comment]
是管理员界面啊，并且有ai币

**Comment by xjy1592922966** [comment]
运营配置， 鼠标滚轮往下

**Comment by liuzhongyyi** [comment]
是功能性设置哪里吗，新用户奖励次数填1，小程序，域名（公网）是填自己的，支付宝的可以不填吧，记忆倍数多少合适

**Comment by xjy1592922966** [comment]
建议20，

**Comment by liuzhongyyi** [comment]
![image](https://github.com/dulaiduwang003/SUPERBOT-GPT-WEB/assets/41277860/272cc731-e2b6-476d-bebf-bedc4bf88864)

**Comment by liuzhongyyi** [comment]
![image](https://github.com/dulaiduwang003/SUPERBOT-GPT-WEB/assets/41277860/2ce0985d-72b8-43ae-bcb9-95784b1e0597)
域名哪里用的是后端地址，然后问啥都只回答这个，是不是要添加代理？

**Comment by xjy1592922966** [comment]
看看日志

**Comment by xjy1592922966** [comment]
java项目日志

**Comment by liuzhongyyi** [comment]
![image](https://github.com/dulaiduwang003/SUPERBOT-GPT-WEB/assets/41277860/49062bea-ddb8-4b39-99cc-7dc4bf35f627)
这个frequency我用sql增加了，应该websocket问题
